# Generated by Django 5.0.7 on 2024-08-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='heroes',
            name='boost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.boost'),
        ),
    ]
